# Generated by Django 6.0.3 on 2026-03-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Richiesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_richiedente', models.CharField(max_length=100)),
                ('reparto', models.CharField(max_length=100)),
                ('ruolo_richiesto', models.CharField(max_length=100)),
                ('motivazione', models.TextField()),
                ('urgenza', models.CharField(max_length=20)),
                ('tipo_richiesta', models.CharField(max_length=100)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
