# Generated by Django 6.0.3 on 2026-03-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='richiesta',
            name='motivo_richiesta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
