# Generated by Django 6.0.3 on 2026-03-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_richiesta_motivo_richiesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='richiesta',
            name='stato',
            field=models.CharField(default='Inserita', max_length=50),
        ),
    ]
