# Generated by Django 6.0.3 on 2026-03-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_motivorichiesta_reparto_ruolo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganicoReparto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reparto', models.CharField(max_length=100)),
                ('ruolo', models.CharField(max_length=100)),
                ('risorse_attuali', models.IntegerField(default=0)),
                ('risorse_previste', models.IntegerField(default=0)),
            ],
        ),
    ]
